import * as esbuild from "esbuild"
import { existsSync, readFileSync, writeFileSync } from "fs"
import { resolve } from "path"
import { solidPlugin } from "esbuild-plugin-solid"

// Generate src/_version.ts when missing (not tracked in git; generated by
// the "version" npm script on release).  Without it the bundle build fails.
const versionFile = resolve("src/_version.ts")
if (!existsSync(versionFile)) {
  const pkg = JSON.parse(readFileSync("package.json", "utf-8"))
  writeFileSync(versionFile, `// auto-generated\nexport const PLUGIN_VERSION=${JSON.stringify(pkg.version)};\n`)
}

await esbuild.build({
  entryPoints: ["src/index.tsx"],
  outfile: "dist/tui.js",
  format: "esm",
  platform: "node",
  bundle: true,
  external: ["@opencode-ai/*", "@opentui/*", "solid-js"],
  plugins: [solidPlugin({ moduleName: "@opentui/solid", generate: "universal" })],
})
